branch-defaults:
  default:
    environment: dev-env
    group_suffix: null
global:
  application_name: hackaton
  branch: null
  default_ec2_keyname: null
  default_platform: php5.5
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
